### ISSUE TITLE
Don't count for the capital letter

### ISSUE THREAD

**Issue by phannawich** [llarall/MicroserviceA#1]
Your code is already perfect and meet the requirement that I gave you earlier.

However, I just found that your code does not work along with my intention.

If you want, can you please add .lower() to the comparison.

I want your microservice to ingore the mistake by typing with capital letter or small letter

For example, If prompt said Hello and user's type is hello.
I want to count as 1/1 because I ignore the capital letter.

If you think what you have done is already met the requirement and it is not you part to fix this. That is fine, thank you

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the count_matching_words function to convert words to lowercase before comparison, making the matching process case-insensitive.

You can review changes in this commit: https://github.com/lkilu6456546/llarall-MicroserviceA-1/commit/55c90d58b13ee311dcb4f7b099f35152df9b456c.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by llarall** [comment]
Should be fixed
